Feature/staked chart for weekly
harvestfi/farmdashboard pull request #105
Opened 2021-07-12 15:13 UTC by dmitrylineup

- added tabs for weekly profit dialog
 - added staked area chart for Weekly profit
 - empty values generated for missed time in each data series

2021-07-14 16:22 UTC, belbix commented on src/app/modules/dialogs/weekly-profit-dialog/weekly-profit-dialog.component.ts
> +                  stack: '总量',
?

2021-07-14 16:30 UTC, belbix commented on src/app/modules/dialogs/weekly-profit-dialog/weekly-profit-dialog.component.ts
> +      const underscoreCount = vaultName.split('_').length;
I had mistake when provided this method
use
      const underscoreCount = vaultName.split('_')?.length ?? 0;
      let platform = 'SINGLE';
      if (underscoreCount > 1) {

2021-07-14 16:43 UTC, belbix commented on src/app/modules/dialogs/weekly-profit-dialog/weekly-profit-dialog.component.ts
> +                          value = j.weeklyAllProfit / 1000;
let's use fullRewardUsdTotal cumulative values
fullRewardUsdTotal - it is a cumulative sum of progits for 1 vault in USD

2021-08-02 20:02 UTC, dmitry2199 requested changes
In general looks good, but some changes are required to be done: 
* It is definitely needs to update tabs rendering, because current tabs implementation is very simple and non extendable.
* Also I'm wondering why you've changed `.loading-screen` styles? If it is used only for dev purpose, then please remove it.

2021-08-15 15:36 UTC, dmitry2199 approved these changes

2021-08-15 16:14 UTC, dmitry2199 requested changes
Changed to ON HOLD according to conversation with @belbix

2021-09-24 10:32 UTC, closed without merging